version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
    - "2183:2183"
  kafka:
    image: wurstmeister/kafka
    ports:
    - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "test_topic:1:3"
    depends_on:
        - zookeeper
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27018:27018'
